spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.200.104:3306/vmp_ar?useUnicode=true&characterEncoding=UTF8
        driver-class-name: com.mysql.jdbc.Driver
        username: vmp
        password: Vmp.2017
        hikari:
            maximum-pool-size: 5
            max-lifetime: 1800000
    ## redis config
    redis:
        host: 192.168.201.174
        port: 6379
        database: 0
        timeout: 5000
        jedis:
            pool:
                max-idle: 20
                max-active: 8
                min-idle: 0


